// #define PROJ_GAMEBOY 1
// #define PROJ_DEVELOPER_MODE 1
#define PROJ_STREAMING_MUSIC 0
#define DISABLE_SOUND_WARNING
#define PROJ_ENABLE_SOUND 0
// #define PROJ_SHOW_FPS_COUNTER

#define PROJ_TILEDMODE 1
#define POK_BITFRAME 0
